# Generated by Django 2.1.5 on 2019-01-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(max_length=10, verbose_name='栏目名称')),
                ('col_alias', models.CharField(max_length=20, verbose_name='栏目别名')),
                ('p_node', models.CharField(max_length=20, verbose_name='父节点')),
                ('key_word', models.CharField(max_length=10, verbose_name='关键字')),
                ('describe', models.CharField(max_length=255, verbose_name='描述')),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='column.Column', verbose_name='所属栏目')),
            ],
            options={
                'db_table': 'column',
            },
        ),
    ]
